ALTER TABLE users ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN whatsapp TEXT NOT NULL DEFAULT '';
ALTER TABLE store_profiles ADD COLUMN business_email TEXT NOT NULL DEFAULT '';
